### ISSUE TITLE
Offtopic

### ISSUE THREAD

**Issue by Chiroyce1** [kccuber-scratch/ScratchTester-v2#3]
hey do you mind telling how much ram project id [621669729](https://llk.github.io/scratch-gui/develop/#621669729) takes up when running? i was trying to make a new project and i think i found a memory leak issue, since you have 48GB RAM, can you run the test multiple times as well? thanks and sorry for this offtopic issue _(this was the only way i could contact you outside of scratch)_

**Comment by Chiroyce1** [comment]
@kccuber-scratch im closing this issue so others dont see it

**Comment by Chiroyce1** [comment]
you can still reply though

**Comment by kccuber-scratch** [comment]
firefox has a really neat memory usage snapshot tool. checking using turbowarp, there does appear to be a slight memory leak issue.
![image](https://user-images.githubusercontent.com/92891642/155852000-e606ebc3-46df-4cd5-b26e-99a05da58cfc.png)
most of the memory seems to be taken up by ArrayBuffer.

**Comment by Chiroyce1** [comment]
so is this a big enough issue that i need to report it to the ST?

**Comment by kccuber-scratch** [comment]
> so is this a big enough issue that i need to report it to the ST?

idk, report if you want
